In [2]:
import pandas as pd
import numpy as np

In [38]:
# set seed
np.random.seed(42)

# number of observations
n = 10000

# number of predictors
p = 10

# make array of dataset
X = np.random.normal(size=(n, p))

# generate target -> 5% is 1's
target = np.random.binomial(1, 0.05, size=n)

# make categorical predictor -> planet
planet = np.random.uniform(0, 1, n)

# choose distribution of planet
planet = np.select(
    [
        planet < 0.3,
        (planet >= 0.3) & (planet < 0.9),
        planet >= 0.9
    ],
    [0, 1, 2])

X[:, 0] = planet

# change up distributions of specific columns
X[:, [2, 3, 8]] = np.random.uniform(0, 1, size=(n, 3))
X[:, 1] = np.random.randint(18, 25, n)
X[:, 4] = np.random.normal(0, 1, n)
X[:, 7] = np.random.exponential(1, n)



# convert to dataframe
df = pd.DataFrame(X, columns=[f"X{i+1}" for i in range(p)])
df["target"] = target

# name predictors
df = df.rename(columns={
    "X1": "planet",   
    "X2": "age"
})

df.head()

,planet,age,X3,X4,X5,X6,X7,X8,X9,X10,target
0,1.0,22.0,0.091222,0.051367,-0.132683,-0.234137,1.579213,1.856237,0.458084,0.542560,0
1,0.0,24.0,0.899470,0.601267,0.285707,-0.562288,-1.012831,0.823519,0.700464,-1.412304,0
2,1.0,24.0,0.888878,0.145362,-2.223487,0.110923,-1.150994,2.245507,0.624967,-0.291694,0
3,2.0,19.0,0.179903,0.786160,-2.220658,-1.220844,0.208864,0.364131,0.767589,0.196861,0
4,2.0,21.0,0.079118,0.943738,-0.212222,-0.719844,-0.460639,1.189172,0.396222,-1.763040,0

In [39]:
# individual counts
print(df["planet"].value_counts())
print(df['target'].value_counts())

planet
1.0    6039
0.0    2892
2.0    1069
Name: count, dtype: int64
target
0    9480
1     520
Name: count, dtype: int64

In [32]:
# percentage of planet and target
pd.crosstab(df["planet"], df["target"], normalize='index')

target         0         1
planet
0.0     0.946750  0.053250
1.0     0.947673  0.052327
2.0     0.953227  0.046773

In [ ]:
# save dataframe for use
df.to_csv("toy_data.csv", index=False)